Add instruction section.
googleinterns/step229-2020 pull request #72
Opened 2020-09-18 17:40 UTC by tblanshard

Add a small box on the first page detailing how to set up all the required parts/ permissions.

@andreeanica16 @iht @juliocc - thank you :)

2020-09-18 18:01 UTC, iht submitted a review, later dismissed
LGTM

2020-09-19 08:33 UTC, andreeanica16 requested changes

2020-09-19 08:33 UTC, andreeanica16 commented on src/main/webapp/script.js
> +        console.log(aggregated[category][costs].price);
I think you should delete this :D

2020-09-19 08:33 UTC, andreeanica16 commented on src/main/webapp/script.js
> +  console.log(aggregated);
And these lines as well :D

2020-09-19 08:33 UTC, andreeanica16 commented on src/main/webapp/script.js
> +  console.log(data);
And this line

2020-09-21 10:07 UTC, andreeanica16 approved these changes

2020-09-21 10:08 UTC, merged